'use client';

import { useData } from "@/components/DataContext";
import { Clock, Zap, TrendingUp, ChevronRight } from "lucide-react";

const BLUE = '#4263eb';

const diffColor = (d: string) => d === 'Easy' ? '#2f9e44' : d === 'Medium' ? '#e67700' : '#c92a2a';
const diffBg    = (d: string) => d === 'Easy' ? '#ebfbee' : d === 'Medium' ? '#fff9db' : '#fff5f5';
const potColor  = (p: string) => p === 'High' ? '#2f9e44' : p === 'Medium' ? '#e67700' : '#868e96';
const potBg     = (p: string) => p === 'High' ? '#ebfbee' : p === 'Medium' ? '#fff9db' : '#f8f9fa';

const card: React.CSSProperties = {
  background: '#fff', borderRadius: 20,
  border: '1px solid rgba(0,0,0,0.06)', boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
};

export default function ModernIdeas() {
  const { ideas } = useData();

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 24 }}>
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 800, color: '#1a1a2e', margin: '0 0 4px', letterSpacing: '-0.03em' }}>AI Video Ideas</h1>
          <p style={{ fontSize: 13, color: '#868e96', margin: 0 }}>Generated by Sarie based on your account data & trends</p>
        </div>
        <button style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 18px', borderRadius: 12, background: '#1a1a2e', border: 'none', color: '#fff', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>
          <Zap size={13} /> Generate More
        </button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16 }}>
        {(ideas.length ? ideas : []).map((idea: any) => (
          <div key={idea.id} style={{ ...card, display: 'flex', flexDirection: 'column' }}>
            {/* Difficulty + potential banner */}
            <div style={{ padding: '16px 20px 0', display: 'flex', gap: 8 }}>
              <span style={{ fontSize: 11, fontWeight: 700, padding: '4px 10px', borderRadius: 100, background: diffBg(idea.difficulty), color: diffColor(idea.difficulty) }}>{idea.difficulty}</span>
              <span style={{ fontSize: 11, fontWeight: 700, padding: '4px 10px', borderRadius: 100, background: potBg(idea.potential), color: potColor(idea.potential) }}>
                <TrendingUp size={10} style={{ display: 'inline', marginRight: 4 }}/>{idea.potential} Potential
              </span>
            </div>

            <div style={{ padding: '14px 20px 20px', flex: 1, display: 'flex', flexDirection: 'column' }}>
              {/* Hook */}
              <div style={{ fontSize: 15, fontWeight: 800, color: '#1a1a2e', letterSpacing: '-0.02em', lineHeight: 1.4, marginBottom: 16 }}>
                "{idea.hook}"
              </div>

              {/* 3-act structure */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 18 }}>
                {[
                  { label: 'Act 1 — Hook', text: idea.act1 },
                  { label: 'Act 2 — Build', text: idea.act2 },
                  { label: 'Act 3 — Payoff', text: idea.act3 },
                ].map(({ label, text }) => (
                  <div key={label} style={{ background: '#f8f9fa', borderRadius: 10, padding: '10px 14px' }}>
                    <div style={{ fontSize: 10, fontWeight: 700, color: '#adb5bd', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 4 }}>{label}</div>
                    <div style={{ fontSize: 12, color: '#495057', lineHeight: 1.5 }}>{text}</div>
                  </div>
                ))}
              </div>

              {/* Meta */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 18 }}>
                <div style={{ background: '#f8f9fa', borderRadius: 10, padding: '10px 12px' }}>
                  <div style={{ fontSize: 10, color: '#adb5bd', fontWeight: 600, marginBottom: 3 }}>Format</div>
                  <div style={{ fontSize: 12, fontWeight: 600, color: '#1a1a2e' }}>{idea.format}</div>
                </div>
                <div style={{ background: '#f8f9fa', borderRadius: 10, padding: '10px 12px' }}>
                  <div style={{ fontSize: 10, color: '#adb5bd', fontWeight: 600, marginBottom: 3 }}>Audience</div>
                  <div style={{ fontSize: 12, fontWeight: 600, color: '#1a1a2e' }}>{idea.generation}</div>
                </div>
                <div style={{ background: '#f8f9fa', borderRadius: 10, padding: '10px 12px' }}>
                  <div style={{ fontSize: 10, color: '#adb5bd', fontWeight: 600, marginBottom: 3 }}>Sound</div>
                  <div style={{ fontSize: 12, fontWeight: 600, color: '#1a1a2e', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{idea.sound}</div>
                </div>
                <div style={{ background: '#f8f9fa', borderRadius: 10, padding: '10px 12px', display: 'flex', alignItems: 'center', gap: 6 }}>
                  <Clock size={11} color="#adb5bd" />
                  <div>
                    <div style={{ fontSize: 10, color: '#adb5bd', fontWeight: 600 }}>Best Time</div>
                    <div style={{ fontSize: 11, fontWeight: 600, color: '#1a1a2e' }}>{idea.bestTime}</div>
                  </div>
                </div>
              </div>

              {/* Caption preview */}
              <div style={{ background: '#eef2ff', borderRadius: 10, padding: '10px 14px', marginBottom: 16 }}>
                <div style={{ fontSize: 10, fontWeight: 700, color: BLUE, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 4 }}>Caption</div>
                <div style={{ fontSize: 11, color: '#495057', lineHeight: 1.5 }}>{idea.caption}</div>
              </div>

              <button style={{ display: 'flex', alignItems: 'center', gap: 6, width: '100%', padding: '10px 16px', borderRadius: 12, background: '#1a1a2e', border: 'none', color: '#fff', fontSize: 12, fontWeight: 700, cursor: 'pointer', marginTop: 'auto' }}>
                <span style={{ flex: 1, textAlign: 'left' }}>Use this idea</span>
                <ChevronRight size={14} />
              </button>
            </div>
          </div>
        ))}

        {/* Placeholder if no ideas */}
        {(!ideas || ideas.length === 0) && (
          <div style={{ gridColumn: 'span 3', textAlign: 'center', padding: '60px 0', color: '#adb5bd', fontSize: 14 }}>
            No ideas yet — ask Sarie to generate some based on your account data.
          </div>
        )}
      </div>
    </div>
  );
}
