export const mockAccount = {
  username: "@mas.studio",
  followers: 48200,
  followersGrowth: 1200,
  avgEngagement: 6.8,
  engagementChange: 0.4,
  weeklyViews: 312000,
  weeklyViewsChange: -8,
  actionItems: 4,
}

export const mockVideos: any[] = [
  {
    id: "1",
    title: "How we built a studio in 30 days",
    thumbnail: null,
    views: 142000,
    likes: 9800,
    comments: 312,
    shares: 540,
    posted: "2025-04-14",
    score: 82,
    hook: 70,
    pacing: 88,
    caption: 85,
    hashtags: 90,
    cta: 65,
    duration: 60,
    tone: "Informative / Valuable",
    emotionalPull: 38,
    energy: 75,
    retentionRisk: "Low",
    growthPotential: 72,
    weaknessFlags: ["No Discussion"],
    sound: 72, soundType: "Original Sound", soundName: "Original Audio — MAS Studio",
    soundIssue: "Sound strategy is working — original audio fits the studio content well.",
    soundSuggestion: "Consider building a consistent audio identity — use the same lofi track as a signature intro across episodes.",
    appearance: 82, appearanceIssue: null,
    filming: 85,
    content: 88,
    mood: "Serious / Focus",
    issue: "Hook is too slow — first 2 seconds don't grab attention",
    suggestion: "Start with the finished studio reveal, then cut to day 1. Lead with the transformation.",
  },
  {
    id: "2",
    title: "AI tools we use every day",
    thumbnail: null,
    views: 89000,
    likes: 6100,
    comments: 198,
    shares: 320,
    posted: "2025-04-11",
    score: 71,
    hook: 80,
    pacing: 75,
    caption: 70,
    hashtags: 65,
    cta: 45,
    duration: 45,
    tone: "Informative / Valuable",
    emotionalPull: 22,
    energy: 78,
    retentionRisk: "Low",
    growthPotential: 65,
    weaknessFlags: ["No Discussion", "Weak CTA"],
    sound: 80, soundType: "Trending Audio", soundName: "Lofi Study Beats — ChillHop",
    soundIssue: "Sound strategy is working — trending lofi suits the informative AI content well.",
    soundSuggestion: "Maintain the lofi identity. Consider using the same track across your AI series to build audio branding.",
    appearance: 75, appearanceIssue: "Lighting slightly uneven — left side of face has a faint shadow.",
    filming: 70,
    content: 72,
    mood: "Upbeat",
    issue: "No clear CTA — video ends abruptly",
    suggestion: "Add a final 3-second card: 'Follow for weekly AI tool drops' with text overlay.",
  },
  {
    id: "3",
    title: "Client results after 1 month",
    thumbnail: null,
    views: 21000,
    likes: 890,
    comments: 44,
    shares: 67,
    posted: "2025-04-08",
    score: 44,
    hook: 40,
    pacing: 50,
    caption: 35,
    hashtags: 30,
    cta: 55,
    duration: 90,
    tone: "Flat / Boring",
    emotionalPull: 8,
    energy: 42,
    retentionRisk: "High",
    growthPotential: 28,
    weaknessFlags: ["Low Likes", "Not Shareable", "No Discussion", "Low Engagement", "No Audio"],
    sound: 28, soundType: "No Audio", soundName: "Unknown",
    soundIssue: "No background audio detected — missing a key TikTok discoverability signal on the For You page.",
    soundSuggestion: "Add a soft lofi track from TikTok's Creator Tools library. Keep music at 10–15% volume relative to voice so speech stays clear.",
    appearance: 48, appearanceIssue: "Outfit too casual for professional content. Background is cluttered and distracting. No visible lighting setup.",
    filming: 55,
    content: 60,
    mood: "Casual",
    issue: "Flat content — near-zero emotional reaction. The video fails to trigger any share or comment behavior. Hook isn't stopping the scroll.",
    suggestion: "Rebuild video structure: shock/question hook in second 1, build tension or story in the middle, deliver an emotional payoff at the end. Add text overlays every 8–10s.",
  },
  {
    id: "4",
    title: "Behind the scenes: shoot day",
    thumbnail: null,
    views: 67000,
    likes: 5200,
    comments: 231,
    shares: 410,
    posted: "2025-04-05",
    score: 78,
    hook: 85,
    pacing: 80,
    caption: 75,
    hashtags: 72,
    cta: 60,
    duration: 35,
    tone: "Entertaining / Likeable",
    emotionalPull: 48,
    energy: 85,
    retentionRisk: "Low",
    growthPotential: 70,
    weaknessFlags: ["No Discussion"],
    sound: 85, soundType: "Trending Audio", soundName: "Aesthetic Vlog — Artlist",
    soundIssue: "Sound strategy is working — upbeat vlog audio matches the behind-the-scenes energy perfectly.",
    soundSuggestion: "Good choice. Keep using this style of audio for BTS content — it reinforces the brand aesthetic.",
    appearance: 88, appearanceIssue: null,
    filming: 90,
    content: 92,
    mood: "Energetic",
    issue: "Good pacing but caption is too long",
    suggestion: "Cut caption to 1 punchy line + 3 hashtags max. Long captions hide the hook on mobile.",
  },
  {
    id: "5",
    title: "3 mistakes every brand makes",
    thumbnail: null,
    views: 38000,
    likes: 2900,
    comments: 145,
    shares: 220,
    posted: "2025-04-02",
    score: 60,
    hook: 75,
    pacing: 65,
    caption: 55,
    hashtags: 50,
    cta: 50,
    duration: 70,
    tone: "Informative / Valuable",
    emotionalPull: 28,
    energy: 60,
    retentionRisk: "Medium",
    growthPotential: 55,
    weaknessFlags: ["No Discussion", "Weak Caption"],
    sound: 62, soundType: "Original Sound", soundName: "Original Audio — MAS Studio",
    soundIssue: "Using original sound but engagement is weak — original audio only works when the hook is exceptionally strong.",
    soundSuggestion: "Layer a low-volume trending background track under the original voice audio. Test a popular lofi or podcast instrumental.",
    appearance: 70, appearanceIssue: "Outfit color blends with background — add contrast. Consider a solid-color top.",
    filming: 74,
    content: 80,
    mood: "Serious / Focus",
    issue: "Caption too long, hashtags too generic",
    suggestion: "Replace #marketing with niche-specific tags. Rewrite caption as: '3 mistakes killing your reach (and the fix)'.",
  },
  {
    id: "6",
    title: "Why your TikTok reach dropped",
    thumbnail: null,
    views: 54000,
    likes: 4100,
    comments: 189,
    shares: 290,
    posted: "2025-03-29",
    score: 74,
    hook: 82,
    pacing: 78,
    caption: 68,
    hashtags: 61,
    cta: 55,
    duration: 50,
    tone: "Informative / Valuable",
    emotionalPull: 25,
    energy: 68,
    retentionRisk: "Low",
    growthPotential: 60,
    weaknessFlags: ["No Discussion"],
    sound: 76, soundType: "Trending Audio", soundName: "Focus Mode — Lo-Fi Beats",
    soundIssue: "Sound is present and fits well. Not fully optimized for reach.",
    soundSuggestion: "Consider testing a currently trending sound to get an algorithmic boost alongside the good content.",
    appearance: 78, appearanceIssue: "Background slightly busy — simplify or add a branded backdrop.",
    filming: 82,
    content: 81,
    mood: "Upbeat",
    issue: "Hashtags are too broad, not niche-targeted",
    suggestion: "Swap #viral and #fyp for #contentcreatoregypt and #tiktokgrowth.",
  },
  {
    id: "7",
    title: "We went viral — here's what happened",
    thumbnail: null,
    views: 210000,
    likes: 18400,
    comments: 620,
    shares: 1100,
    posted: "2025-03-25",
    score: 91,
    hook: 95,
    pacing: 92,
    caption: 88,
    hashtags: 85,
    cta: 88,
    duration: 45,
    tone: "Emotional / Shareable",
    emotionalPull: 72,
    energy: 90,
    retentionRisk: "Low",
    growthPotential: 88,
    weaknessFlags: [],
    sound: 91, soundType: "Trending Audio", soundName: "Viral Sound #4821 — TikTok",
    soundIssue: "Sound strategy is working — trending audio significantly boosted the For You page reach on this video.",
    soundSuggestion: "This is the blueprint. Identify a trending sound within 48h of it going viral and pair it with strong content.",
    appearance: 92, appearanceIssue: null,
    filming: 94,
    content: 90,
    mood: "Energetic",
    issue: "Near-perfect but CTA could be stronger",
    suggestion: "Pinch the CTA: 'Save this for when you need it' drives 40% more saves than generic CTAs.",
  },
  {
    id: "8",
    title: "Day 1 vs Day 365 at MAS",
    thumbnail: null,
    views: 44000,
    likes: 3200,
    comments: 98,
    shares: 160,
    posted: "2025-03-22",
    score: 56,
    hook: 60,
    pacing: 58,
    caption: 52,
    hashtags: 45,
    cta: 48,
    duration: 95,
    tone: "Neutral",
    emotionalPull: 18,
    energy: 48,
    retentionRisk: "Medium",
    growthPotential: 45,
    weaknessFlags: ["No Discussion", "Too Long"],
    sound: 55, soundType: "Original Sound", soundName: "Original Audio — MAS Studio",
    soundIssue: "Original sound with a long video and medium engagement — audio isn't compensating for the retention drop.",
    soundSuggestion: "Add a subtle trending background track and cut the video length. The audio needs to help carry energy through the middle section.",
    appearance: 65, appearanceIssue: "Lighting drops in quality mid-video. Outfit is fine but consider adding a lapel mic for cleaner audio presentation.",
    filming: 68,
    content: 70,
    mood: "Casual",
    issue: "Video is 95s long but engagement is only 7.5% — viewers are dropping off early. Content isn't holding attention past the opening seconds.",
    suggestion: "Cut to ~57s. Lead with the most valuable moment. Use jump cuts every 8–10s. Add text overlays to reinforce key points and maintain energy.",
  },
  {
    id: "9",
    title: "5 tools that 10x'd our output",
    thumbnail: null,
    views: 76000,
    likes: 5900,
    comments: 221,
    shares: 380,
    posted: "2025-03-18",
    score: 80,
    hook: 88,
    pacing: 82,
    caption: 76,
    hashtags: 70,
    cta: 62,
    duration: 55,
    tone: "Informative / Valuable",
    emotionalPull: 35,
    energy: 76,
    retentionRisk: "Low",
    growthPotential: 68,
    weaknessFlags: [],
    sound: 82, soundType: "Trending Audio", soundName: "Productivity Lofi — ChillHop",
    soundIssue: "Sound strategy is working — lofi productivity audio fits the tools content well.",
    soundSuggestion: "This audio pairing works. Replicate it across your educational content series for consistent audio branding.",
    appearance: 84, appearanceIssue: null,
    filming: 86,
    content: 85,
    mood: "Upbeat",
    issue: "CTA is buried — viewers miss it",
    suggestion: "Move CTA to both the 5-second and final-second marks for double exposure.",
  },
  {
    id: "10",
    title: "What clients don't tell you",
    thumbnail: null,
    views: 29000,
    likes: 2100,
    comments: 77,
    shares: 130,
    posted: "2025-03-15",
    score: 52,
    hook: 55,
    pacing: 60,
    caption: 45,
    hashtags: 40,
    cta: 42,
    duration: 40,
    tone: "Neutral",
    emotionalPull: 20,
    energy: 58,
    retentionRisk: "Low",
    growthPotential: 48,
    weaknessFlags: ["No Discussion", "Low Likes"],
    sound: 58, soundType: "Original Sound", soundName: "Original Audio — MAS Studio",
    soundIssue: "Original sound with low engagement — the audio alone isn't carrying the video through a weak hook.",
    soundSuggestion: "Pair the original voice with a subtle trending background track to boost discoverability while keeping authenticity.",
    appearance: 72, appearanceIssue: "Good outfit but background is plain white wall — add a branded element or soft lighting accent.",
    filming: 75,
    content: 68,
    mood: "Casual",
    issue: "Hook doesn't create curiosity or tension",
    suggestion: "Rewrite hook: 'A client fired us after 3 weeks. Here's what we learned.' — tension drives watch time.",
  },
] as const

export const mockGenerations: any[] = [
  { label: "Gen Z", pct: 52, color: "#D4537E" },
  { label: "Millennials", pct: 31, color: "#378ADD" },
  { label: "Gen X", pct: 12, color: "#5DCAA5" },
  { label: "Boomers", pct: 5, color: "#888780" },
] as const

export const mockTrends: any[] = [
  { rank: 1, name: "Day in my life (agency edition)", type: "format", views: "2.1B" },
  { rank: 2, name: "POV: you hired an agency", type: "format", views: "440M" },
  { rank: 3, name: "Before & after transformation", type: "format", views: "1.4B" },
  { rank: 4, name: "Things I wish I knew earlier", type: "hook", views: "3.2B" },
  { rank: 5, name: "Trending lo-fi beat #4821", type: "sound", views: "890M" },
] as const

export const mockCompetitors: any[] = [
  {
    handle: "@visualcraft.eg",
    followers: 112000,
    postsThisWeek: 3,
    viewChange: "+18K",
    status: "spiking",
    avgViews: 42000,
    topFormat: "Behind the scenes",
  },
  {
    handle: "@pixelmade",
    followers: 67000,
    postsThisWeek: 1,
    viewChange: "stable",
    status: "stable",
    avgViews: 28000,
    topFormat: "Educational lists",
  },
  {
    handle: "@createroom.eg",
    followers: 89000,
    postsThisWeek: 5,
    viewChange: "+31K",
    status: "spiking",
    avgViews: 36000,
    topFormat: "DITL / Day in the life",
  },
] as const

export const mockIdeas: any[] = [
  {
    id: "1",
    hook: "POV: a client came to us with zero presence — here's week 1",
    format: "Before & after",
    act1: "Show the client's empty social profile / zero followers",
    act2: "Walk through the strategy we built in 48 hours",
    act3: "Reveal week 1 results — views, engagements, first viral moment",
    generation: "Gen Z",
    sound: "Trending lo-fi beat",
    caption: "From 0 to real results in 7 days. This is what we actually did. #agencylife #contentmarketing #brandgrowth",
    bestTime: "7:00 PM – 9:00 PM",
    difficulty: "Easy",
    potential: "High",
  },
  {
    id: "2",
    hook: "3 things Egyptian brands do that kill their reach (and how to fix them)",
    format: "List / educational",
    act1: "Introduce the 3 mistakes with bold text overlays",
    act2: "Show real examples of each mistake with quick fixes",
    act3: "Call to action: 'Which one are you guilty of? Comment below'",
    generation: "Millennials",
    sound: "Upbeat background music",
    caption: "Stop doing #3 immediately. #marketing #egyptianbusiness #socialmediatips",
    bestTime: "12:00 PM – 2:00 PM",
    difficulty: "Medium",
    potential: "High",
  },
  {
    id: "3",
    hook: "Day in the life at MAS studio — but make it chaotic",
    format: "DITL",
    act1: "Chaotic morning — 5 clients, 3 deadlines, 1 broken camera",
    act2: "How the team handles it — systems, tools, mindset",
    act3: "End with the win: content delivered, client happy, team exhausted but proud",
    generation: "All",
    sound: "Viral audio of the week",
    caption: "Nobody told us running a studio would look like this. #behindthescenes #studiolife #mas",
    bestTime: "6:00 PM – 8:00 PM",
    difficulty: "Easy",
    potential: "Medium",
  },
] as const
