export const mockAccount = {
  username: "@mas.studio",
  followers: 48200,
  followersGrowth: 1200,
  avgEngagement: 6.8,
  engagementChange: 0.4,
  weeklyViews: 312000,
  weeklyViewsChange: -8,
  actionItems: 4,
}

export const mockVideos: any[] = [
  {
    "id": "7299071591109922054",
    "title": "ساعات الإهتمام بيطلب   #podcast  #rasayel   #fypシ ...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-maliva-p-0068/ooxihg7vEZzCkHpAkLJBfgsIDIAiA8coiPQyIc~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=xPMwc5OnZPfT4VwAxUH8YGHSNr8%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 1400000,
    "likes": 48400,
    "comments": 402,
    "shares": 4969,
    "posted": "2023-11-08",
    "duration": 77,
    "score": 92,
    "hook": 95,
    "pacing": 90,
    "caption": 88,
    "hashtags": 75,
    "cta": 0,
    "tone": "Reflective",
    "emotionalPull": 95,
    "energy": 45,
    "retentionRisk": "Low",
    "growthPotential": 98,
    "weaknessFlags": [
      "No CTA",
      "Distracting Branding"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "ساعات الإهتمام بيطلب",
    "soundIssue": null,
    "soundSuggestion": "The combination of clear vocal audio and emotional background music is highly effective. No changes needed.",
    "appearance": 90,
    "appearanceIssue": "The large, transparent 'رسائل' logo overlaid in the center of the video is distracting and covers the speaker's face during transitions.",
    "filming": 93,
    "mood": "Introspective and thoughtful",
    "issue": "The primary issue is the placement of the channel's branding, which is overlaid on the main subject (the speaker) and can be distracting for the viewer.",
    "suggestion": "Keep the 'رسائل' logo for branding, but make it smaller and place it in a fixed position in one of the corners (e.g., top left). This ensures brand visibility without interfering with the viewing experience."
  },
  {
    "id": "7285100509659188486",
    "title": "#الأب ...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-maliva-p-0068/okqZOtojNAESSAMhAzIy0FAg4hgkfCHV2POIJE~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=%2FqE2h1gY%2B0EutdpyAIm9kX%2Bik8s%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 1000000,
    "likes": 33500,
    "comments": 679,
    "shares": 1937,
    "posted": "2023-10-01",
    "duration": 35,
    "score": 92,
    "hook": 98,
    "pacing": 95,
    "caption": 70,
    "hashtags": 75,
    "cta": 10,
    "tone": "Melancholic",
    "emotionalPull": 100,
    "energy": 20,
    "retentionRisk": "Low",
    "growthPotential": 95,
    "weaknessFlags": [
      "No CTA",
      "Minimal Caption",
      "No Branding"
    ],
    "sound": 98,
    "soundType": "Original Sound",
    "soundName": "Original Audio",
    "soundIssue": null,
    "soundSuggestion": "The combination of the emotional voice and the background music is perfectly balanced and highly effective.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Heartbreaking and reflective",
    "issue": "The video achieves a massive emotional impact but lacks a clear Call-To-Action or branding, missing an opportunity to convert the highly engaged viewers into followers or direct them to more content.",
    "suggestion": "Incorporate a subtle, non-intrusive brand logo in one of the corners. Add a simple CTA in the caption, such as 'شاهد الحلقة الكاملة لتسمع القصة' to guide interested viewers to the full episode."
  },
  {
    "id": "7633813409615580437",
    "title": "أكتر نعمة بتتنسي كل يوم🤍\nشوف الحلقة كاملة في البا...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oorFaECAIVRcHDAdffkGhQMLpbAg4DrU8AEgAB~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=rtQg%2Big3BF6Gs0GrDZexX96wHRo%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 311,
    "likes": 20,
    "comments": 1,
    "shares": 0,
    "posted": "2026-04-28",
    "duration": 43,
    "score": 88,
    "hook": 95,
    "pacing": 80,
    "caption": 90,
    "hashtags": 90,
    "cta": 95,
    "tone": "Reflective",
    "emotionalPull": 90,
    "energy": 20,
    "retentionRisk": "Low",
    "growthPotential": 85,
    "weaknessFlags": [
      "Obtrusive Watermark"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original Sound",
    "soundIssue": null,
    "soundSuggestion": "The mix of the speaker's clear voice and the subtle background music is excellent and sets the mood perfectly. No changes needed.",
    "appearance": 80,
    "appearanceIssue": "The semi-transparent 'Rasayel' logo is very large and placed directly over the speaker, which can be distracting for the viewer.",
    "filming": 95,
    "mood": "Contemplative and spiritual",
    "issue": "The primary weakness is the branding placement. The large, central watermark detracts from the otherwise professional and clean visuals by covering the speaker.",
    "suggestion": "Keep the strong branding, but reduce the size of the 'Rasayel' logo and relocate it to a corner (like the bottom-left). This will maintain brand visibility without interfering with the viewing experience."
  },
  {
    "id": "7629822378960325909",
    "title": "حتى لو محدش شايف تعبك .. دا مش معناه إن اللي بتمر ...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o4xCAeAuMIAKPRzSN5kTivBdywi3NABH0IOIEi~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=8oUq8kaYWh4tbVBrjTSj%2Fr3sVUQ%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 679,
    "likes": 42,
    "comments": 8,
    "shares": 1,
    "posted": "2026-04-17",
    "duration": 42,
    "score": 68,
    "hook": 85,
    "pacing": 90,
    "caption": 80,
    "hashtags": 50,
    "cta": 10,
    "tone": "Supportive",
    "emotionalPull": 90,
    "energy": 15,
    "retentionRisk": "Medium",
    "growthPotential": 75,
    "weaknessFlags": [
      "No CTA",
      "Generic Hashtags",
      "Low Engagement"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": null,
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 90,
    "mood": "Introspective",
    "issue": "The video provides a powerful message but fails to actively engage the viewer or reach a targeted audience. The hashtags are too broad, and the absence of a Call to Action (CTA) makes the experience passive, limiting potential for comments, shares, and follows.",
    "suggestion": "Incorporate a soft CTA at the end of the video or in the caption, such as 'Share this with someone who needs to hear it' or 'Follow for more messages that touch the heart.' Additionally, enhance the hashtag strategy by including niche-specific Arabic tags like #صحة_نفسية (mental health), #تحفيز (motivation), or #كلام_من_القلب (words from the heart) to attract a more relevant audience."
  },
  {
    "id": "7629400037365255445",
    "title": "انت مهم .. حتى في أصعب لحظاتك🤍\nمفيش حاجة تستاهل ت...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oMiEPfoggUGpKAfBfFvnASeYAZQhIGy84EhRPc~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=KatUQQrLd45udmmQb8Onm5eU3QM%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 883,
    "likes": 32,
    "comments": 5,
    "shares": 0,
    "posted": "2026-04-16",
    "duration": 156,
    "score": 58,
    "hook": 85,
    "pacing": 30,
    "caption": 85,
    "hashtags": 50,
    "cta": 90,
    "tone": "Empathetic",
    "emotionalPull": 95,
    "energy": 10,
    "retentionRisk": "High",
    "growthPotential": 25,
    "weaknessFlags": [
      "Too Long",
      "Slow Pacing",
      "Poor Format-Platform Fit"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "الصوت ممتاز، لكن لزيادة الانتشار، يمكن تجربة استخدام مقاطع صوتية مؤثرة ورائجة (Trending Sounds) كخلفية بصوت منخفض مع الحفاظ على الصوت الأصلي.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 70,
    "mood": "Somber and reflective",
    "issue": "المشكلة الأساسية هي عدم ملاءمة صيغة الفيديو لمنصة تيك توك. الفيديو طويل جدًا (أكثر من دقيقتين) وإيقاعه بطيء جدًا، أشبه بمقطع من بودكاست أو برنامج يوتيوب، مما يجعله غير جذاب لمستخدمي تيك توك الباحثين عن محتوى سريع وديناميكي، وهذا يفسر ضعف المشاهدات والتفاعل.",
    "suggestion": "يجب إعادة توظيف المحتوى بتقسيمه إلى عدة مقاطع تيك توك قصيرة (15-45 ثانية). كل مقطع يركز على فكرة واحدة قوية ومؤثرة، مثل (أثر كلمات الأب) أو (قصص حب انتهت) مع استخدام مونتاج أكثر ديناميكية مثل تقريب الصورة (Zoom) على المتحدثة للتأكيد، وإضافة نصوص متحركة كبيرة لإبراز الجمل الرئيسية. هذا سيحسن الإيقاع ومعدل الاحتفاظ بالجمهور على المنصة."
  },
  {
    "id": "7625715522755235092",
    "title": "شوف شكل طفلك بقى ايه في 2030!!\nشوفوا حلقة حتى تبقى...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oAADA0wnezTQfE9AoGDf1InBop9jEuFAA0lIMn~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=JrG7WOl5LOD5Ph6FQiCZEF%2BjjGo%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 560,
    "likes": 27,
    "comments": 3,
    "shares": 0,
    "posted": "2026-04-06",
    "duration": 64,
    "score": 85,
    "hook": 80,
    "pacing": 90,
    "caption": 75,
    "hashtags": 50,
    "cta": 95,
    "tone": "Cautionary",
    "emotionalPull": 90,
    "energy": 70,
    "retentionRisk": "Low",
    "growthPotential": 90,
    "weaknessFlags": [
      "Generic Hashtags"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original Sound",
    "soundIssue": null,
    "soundSuggestion": "The audio quality is excellent, and the use of suspenseful background music effectively enhances the serious and ominous mood.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Ominous",
    "issue": "The video's discoverability is hindered by the use of overly generic hashtags (#fyp, #viral) which don't target the specific audience most interested in the topic (parents, educators).",
    "suggestion": "Utilize a mix of broad and niche Arabic hashtags relevant to the content, such as #تربية_الأبناء, #الصحة_النفسية_للطفل, #مخاطر_السوشيال_ميديا, and #بودكاست_عربي to ensure the video reaches its target demographic."
  },
  {
    "id": "7624952049410559252",
    "title": "ازاي نحافظ على ولادنا من الانحرافات السلوكية؟\nشوفو...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o8D0cEOIDoMTUCRLgEfMA4AAzFSYApBEdevRYR~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=XIEcoP1wdN0q1P%2BcX3sbtnKl4Sc%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 263,
    "likes": 16,
    "comments": 2,
    "shares": 0,
    "posted": "2026-04-04",
    "duration": 97,
    "score": 45,
    "hook": 50,
    "pacing": 40,
    "caption": 70,
    "hashtags": 30,
    "cta": 65,
    "tone": "Academic",
    "emotionalPull": 80,
    "energy": 35,
    "retentionRisk": "High",
    "growthPotential": 25,
    "weaknessFlags": [
      "Low Energy",
      "Slow Pacing",
      "Generic Hashtags",
      "Static Shot"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "إضافة موسيقى تصويرية خافتة وذات طابع جاد أو وثائقي لزيادة الإحساس بالأهمية والمساعدة في الحفاظ على انتباه المشاهد.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 85,
    "mood": "جاد وتحليلي",
    "issue": "المحتوى ذو طابع أكاديمي وبطيء لا يتناسب مع طبيعة منصة تيك توك السريعة. الفيديو عبارة عن مقطع طويل من بودكاست دون تعديلات جوهرية لجعله أكثر جاذبية، مما يؤدي إلى فقدان اهتمام المشاهد بسرعة، وهو ما تعكسه أرقام المشاهدات والتفاعل المنخفضة.",
    "suggestion": "يجب إعادة صياغة المحتوى ليناسب تيك توك. بدلاً من مقطع طويل، يمكن إنشاء فيديوهات أقصر (15-30 ثانية) تركز كل منها على فكرة واحدة قوية ومثيرة للجدل من النقاش. استخدموا عناوين نصية متحركة (Dynamic Captions) وموسيقى خلفية مناسبة لرفع مستوى الطاقة. الأهم هو استخدام هاشتاجات دقيقة وموجهة (مثل #الهوية_الوطنية، #تربية_الأبناء، #الأمن_القومي) للوصول إلى الجمهور المهتم بهذه المواضيع الجادة."
  },
  {
    "id": "7623462150144642324",
    "title": "الألوان وعلاقتها بالمثلية!\nشوفوا حلقة حتى تبقى اله...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oAOPXA1OfQBu4IQnuLLeGFAfY96ONCQeGnGGRn~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=GYEb98Bq%2BfyG5aIaOhsBB%2FZhuAU%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 119,
    "likes": 12,
    "comments": 2,
    "shares": 0,
    "posted": "2026-03-31",
    "duration": 121,
    "score": 80,
    "hook": 95,
    "pacing": 70,
    "caption": 75,
    "hashtags": 40,
    "cta": 85,
    "tone": "Informative",
    "emotionalPull": 85,
    "energy": 30,
    "retentionRisk": "Medium",
    "growthPotential": 90,
    "weaknessFlags": [
      "Static Visuals",
      "Generic Hashtags",
      "Long Format"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "The audio is excellent. Consider adding a very subtle, non-intrusive instrumental track in the background to maintain mood and engagement.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 90,
    "mood": "Serious & Intellectual",
    "issue": "The video uses a static 'talking head' podcast format, which can struggle to retain audience attention on a visually dynamic platform like TikTok, despite the compelling topic.",
    "suggestion": "To boost retention, integrate dynamic visuals. Use animated text to highlight key terms like 'كود جيني' or 'سلوك حيواني'. Incorporating relevant B-roll or stock footage when discussing concepts like animal behavior would make the content more visually engaging."
  },
  {
    "id": "7623053333703544084",
    "title": "حمايتي لإبني كانت غلط!!\nشوفوا حلقة تجنيد الطفولة ع...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/ocyAWCEoguDARxgkIfAGFDKBflUADpIEgSEAMu~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=tqmS2Uykjoa2xF9ARwC4Tc8erx8%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 489,
    "likes": 33,
    "comments": 1,
    "shares": 0,
    "posted": "2026-03-30",
    "duration": 133,
    "score": 65,
    "hook": 40,
    "pacing": 50,
    "caption": 90,
    "hashtags": 30,
    "cta": 95,
    "tone": "Serious",
    "emotionalPull": 75,
    "energy": 35,
    "retentionRisk": "High",
    "growthPotential": 60,
    "weaknessFlags": [
      "Static Visuals",
      "Slow Pacing",
      "Generic Hashtags"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": "The audio is clear dialogue but lacks a trending background sound, which can limit algorithmic reach.",
    "soundSuggestion": "Consider adding a very low-volume, trending instrumental audio behind the dialogue to potentially boost visibility.",
    "appearance": 85,
    "appearanceIssue": null,
    "filming": 80,
    "mood": "Contemplative",
    "issue": "The video is a direct, lengthy clip from a podcast with static 'talking head' visuals and slow pacing, making it ill-suited for TikTok's fast-paced nature and leading to high retention risk.",
    "suggestion": "Create shorter, punchier clips (15-30 seconds) from the full episode. Start each clip with the most controversial or questioning statement as a powerful hook. Improve engagement by using more specific hashtags related to parenting, psychology, and religion (#تربية_الأبناء, #علم_النفس) to reach the intended audience."
  },
  {
    "id": "7622339738539724053",
    "title": "طفلك هدف يتم استقطابه!!\nشوفوا حلقة تجنيد الطفولة ع...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oMAAGRRnQEfAAGdQo2PfJFfHGDx8gfI8kFsmIA~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=FacUl0EX5u0TlD%2F4DEEMx7sh%2B24%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 49500,
    "likes": 142,
    "comments": 2,
    "shares": 15,
    "posted": "2026-03-28",
    "duration": 129,
    "score": 65,
    "hook": 50,
    "pacing": 45,
    "caption": 80,
    "hashtags": 30,
    "cta": 90,
    "tone": "Serious",
    "emotionalPull": 85,
    "energy": 30,
    "retentionRisk": "High",
    "growthPotential": 70,
    "weaknessFlags": [
      "Long Video",
      "Static Visuals",
      "Weak Hook",
      "Generic Hashtags"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "Consider adding a low-volume, trending suspenseful audio track underneath to potentially boost reach.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 85,
    "mood": "Informative and cautionary",
    "issue": "The long (2+ minutes), slow-paced podcast format is ill-suited for TikTok, leading to a high retention risk and a very low engagement rate (0.28%).",
    "suggestion": "Break this clip into multiple, shorter videos (20-40 seconds). Start each with a stronger, more alarming hook (e.g., 'Warning for parents: The color in your child's game is a red flag'). Use niche hashtags like #علم_نفس_الطفل and #تربية_الأبناء to reach the target audience."
  },
  {
    "id": "7621592421784194325",
    "title": "العميل الخفي ChatGPT! \nشوفوا حلقة تجنيد الطفولة عل...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oMIFgYgxfAEBwVDjADRpYWCeVEBUFEAYiVAI26~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=bi0TeipxciHs3Z687dqAtQtnSYo%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 65000,
    "likes": 217,
    "comments": 4,
    "shares": 81,
    "posted": "2026-03-26",
    "duration": 138,
    "score": 78,
    "hook": 95,
    "pacing": 90,
    "caption": 90,
    "hashtags": 40,
    "cta": 95,
    "tone": "Serious",
    "emotionalPull": 90,
    "energy": 70,
    "retentionRisk": "Medium",
    "growthPotential": 85,
    "weaknessFlags": [
      "Poor Hashtag Strategy",
      "Low Like-to-View Ratio"
    ],
    "sound": 98,
    "soundType": "Original Sound",
    "soundName": "العميل الخفي ChatGPT!",
    "soundIssue": "Missing suspenseful background music",
    "soundSuggestion": "Add a low-volume, suspenseful or investigative background music track to enhance the mood and keep viewers engaged.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Concerning & Informative",
    "issue": "The video's discoverability is severely limited by a generic hashtag strategy, failing to reach its target audience interested in AI and its societal impact.",
    "suggestion": "Revise the hashtag strategy to include specific, relevant tags like #الذكاء_الاصطناعي, #خطر_التكنولوجيا, #ChatGPT, and #تربية_الأبناء. This will help the algorithm show the video to a more engaged and interested audience, likely improving the view-to-like ratio."
  },
  {
    "id": "7620460815048527124",
    "title": "مرض السرعة .. فيروس العالم الجديد\nشوفوا حلقة جاري ...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oI104ABTEABiADw7fCAwI1AiFKBuZXZgFRhIKU~tplv-tiktokx-dmt-logom:tos-alisg-i-0068/ooRI54iDhAoS3BKFCoguUMwEBfA3iAA8nBA0KI.image?dr=9634&x-expires=1777557600&x-signature=uJle5gWe0eh%2FUR7JdXXdgihjQ20%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 770,
    "likes": 51,
    "comments": 1,
    "shares": 1,
    "posted": "2026-03-23",
    "duration": 78,
    "score": 78,
    "hook": 90,
    "pacing": 70,
    "caption": 85,
    "hashtags": 60,
    "cta": 95,
    "tone": "تحليلي",
    "emotionalPull": 80,
    "energy": 45,
    "retentionRisk": "Medium",
    "growthPotential": 85,
    "weaknessFlags": [
      "Low Engagement",
      "Generic Hashtags",
      "Pacing Mismatch for Platform"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "مرض السرعة .. فيروس العالم الجديد",
    "soundIssue": null,
    "soundSuggestion": "إضافة موسيقى خلفية هادئة ودرامية خفيفة قد يعزز من التركيز ويزيد من التأثير العاطفي للمحتوى.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "تأملي",
    "issue": "المشكلة الأساسية تكمن في عدم توافق إيقاع البودكاست الحواري البطيء نسبيًا مع طبيعة منصة تيك توك السريعة، مما قد يؤدي إلى فقدان انتباه المشاهدين بسرعة على الرغم من جودة المحتوى والإنتاج العالية.",
    "suggestion": "لزيادة التفاعل، يُقترح قص المقطع ليكون أقصر (أقل من دقيقة) ويركز بشكل مكثف على الفكرة الأكثر إثارة للجدل 'مرض السرعة'. يمكن أيضًا استخدام مؤثرات نصية أكثر ديناميكية تظهر على الشاشة لتلخيص النقاط الرئيسية بسرعة، مما يساعد على الاحتفاظ بالمشاهد الذي يبحث عن محتوى سريع ومباشر."
  },
  {
    "id": "7619021291156229396",
    "title": "مع إنتهاء الشهر الكريم يارب نكون حمدنا ربنا افتكرن...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oQAAhIAf830Avo7Mm6igBi3CIA3BBwmObEvCuu~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=09GFcGxLek4BuhbNZ66Vu0LI8%2F8%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 438,
    "likes": 28,
    "comments": 4,
    "shares": 0,
    "posted": "2026-03-19",
    "duration": 23,
    "score": 75,
    "hook": 70,
    "pacing": 75,
    "caption": 85,
    "hashtags": 60,
    "cta": 20,
    "tone": "Reflective",
    "emotionalPull": 80,
    "energy": 30,
    "retentionRisk": "Medium",
    "growthPotential": 65,
    "weaknessFlags": [
      "No Strong CTA",
      "Generic Hashtags"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "The audio quality is excellent. Consider adding trending, subtle background music underneath the original audio to potentially boost reach, while ensuring it doesn't overpower the voice.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Introspective",
    "issue": "The video is a high-quality podcast clip but lacks a strong call-to-action or interactive elements, making it a passive viewing experience that may limit engagement and viral potential on TikTok.",
    "suggestion": "Add an interactive text overlay with a question related to the video's theme (e.g., \"What are you most grateful for?\") and include a clear call-to-action in the caption encouraging viewers to share their thoughts in the comments."
  },
  {
    "id": "7618981570556202260",
    "title": "من المؤثر الحقيقي؟\nشوفوا حلقة جاري حذف الهوية | د....",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/okwnPAoD8YcAvGGiAECBUYBviaAwAb3xIsEWi~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=kfrD3QncaCV8a4vVgtq5W39WIfg%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 481,
    "likes": 24,
    "comments": 2,
    "shares": 0,
    "posted": "2026-03-19",
    "duration": 163,
    "score": 65,
    "hook": 90,
    "pacing": 75,
    "caption": 70,
    "hashtags": 20,
    "cta": 90,
    "tone": "Educational",
    "emotionalPull": 70,
    "energy": 30,
    "retentionRisk": "High",
    "growthPotential": 60,
    "weaknessFlags": [
      "Generic Hashtags",
      "Low Energy",
      "Niche Topic"
    ],
    "sound": 90,
    "soundType": "Original Sound",
    "soundName": "من المؤثر الحقيقي؟",
    "soundIssue": null,
    "soundSuggestion": "Consider adding very subtle, non-distracting background music to maintain engagement during the conversational parts.",
    "appearance": 70,
    "appearanceIssue": "The large, semi-transparent title card in the middle of the video, while effective, momentarily obstructs the speaker's face.",
    "filming": 80,
    "mood": "Contemplative",
    "issue": "The video's valuable, niche content is being hindered by the use of overly generic hashtags (#fyp, #viral) which prevents it from reaching its ideal target audience of parents and those interested in psychology and cultural identity.",
    "suggestion": "Replace the generic hashtags with specific, targeted ones relevant to the discussion, such as #تربية_الأبناء, #الهوية_العربية, #علم_النفس_التربوي, #اللغة_العربية. This will signal the algorithm to show the video to users who are genuinely interested in this topic, improving engagement and performance."
  },
  {
    "id": "7618227192681483540",
    "title": "دي لغة تواكب العصر ولا تدمّره؟\nشوفوا حلقة جاري حذف...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oUBQ5UfBAzCL0i7CuH3AADuqi3IAYIQwIIaM8s~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=DXN3CiswQp4%2FHtY%2BddT2%2FA8MJLw%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 863,
    "likes": 38,
    "comments": 3,
    "shares": 1,
    "posted": "2026-03-17",
    "duration": 123,
    "score": 75,
    "hook": 95,
    "pacing": 90,
    "caption": 85,
    "hashtags": 40,
    "cta": 95,
    "tone": "Serious",
    "emotionalPull": 85,
    "energy": 60,
    "retentionRisk": "Medium",
    "growthPotential": 70,
    "weaknessFlags": [
      "Generic Hashtags",
      "Niche Topic"
    ],
    "sound": 100,
    "soundType": "Original Sound",
    "soundName": "دي لغة تواكب العصر ولا تدمّره؟",
    "soundIssue": null,
    "soundSuggestion": "The audio quality is excellent. The subtle background music track is effective in setting a serious tone.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Intellectual & Concerned",
    "issue": "The video's performance is hindered by a weak hashtag strategy. The use of overly generic tags like #viral and #viralvideos fails to target the specific audience interested in nuanced discussions about language, culture, and identity, causing the high-quality content to be lost.",
    "suggestion": "Implement a more targeted hashtag strategy. Combine standard tags like #fyp with specific, relevant ones such as #اللغة_العربية (Arabic language), #الهوية_العربية (Arab identity), #فرانكو_اراب (Franco-Arab), and #تربية (parenting). This will improve discoverability among communities genuinely interested in the topic, sparking the intended debate and increasing engagement."
  },
  {
    "id": "7618161741288983828",
    "title": "الإحساس نعمة🤍\nفذَكّر | نِعم منسية\n#viral #Ramadan...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o4uA0CESZzDAREg1WcA7FR5Bf8UACpIEJfEUEt~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=p7fj%2BEwUX%2FVAno4NehauZpdlgJs%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 278,
    "likes": 22,
    "comments": 3,
    "shares": 1,
    "posted": "2026-03-17",
    "duration": 80,
    "score": 65,
    "hook": 60,
    "pacing": 40,
    "caption": 60,
    "hashtags": 30,
    "cta": 0,
    "tone": "Reflective",
    "emotionalPull": 85,
    "energy": 15,
    "retentionRisk": "High",
    "growthPotential": 40,
    "weaknessFlags": [
      "No CTA",
      "Weak Hashtags",
      "Slow Pacing"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "جودة الصوت احترافية ولا تحتاج لتعديل.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 90,
    "mood": "Spiritual",
    "issue": "تمت تهيئة الفيديو كجزء من بودكاست، بإيقاع بطيء ومدروس. هذا الأسلوب لا يتناسب مع طبيعة TikTok السريعة، مما يؤدي إلى انخفاض معدل الاحتفاظ بالجمهور. بالإضافة إلى ذلك، استراتيجية الهاشتاجات ضعيفة وتفتقر إلى دعوة لاتخاذ إجراء (CTA).",
    "suggestion": "ابدأ الفيديو بسؤال أو جملة صادمة أكثر لجذب الانتباه فوراً (مثل: \"لماذا يعتبر الألم أعظم نعمة؟\"). استخدم تقنيات مونتاج أسرع، مثل القصات السريعة أو التكبير التدريجي للحفاظ على اهتمام المشاهد. أضف دعوة واضحة للمشاركة في نهاية الفيديو (مثل: \"شاركنا رأيك في التعليقات\"). استبدل الهاشتاجات العامة (#viral) بهاشتاجات أكثر تخصصًا تتعلق بالمحتوى الديني والروحي."
  },
  {
    "id": "7617554863500627221",
    "title": "كل نفس بناخده .. نعمة🤍\nفذَكّر | نِعم منسية\n#fyp #...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/okptFqEfQAvmCgKCIbAtyBAUAVFRuUfBYgGD0E~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=dFXBG%2BqfCl0e8rI3ZsF27uCkKC4%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 280,
    "likes": 29,
    "comments": 4,
    "shares": 1,
    "posted": "2026-03-16",
    "duration": 67,
    "score": 75,
    "hook": 6,
    "pacing": 4,
    "caption": 8,
    "hashtags": 5,
    "cta": 0,
    "tone": "Reflective",
    "emotionalPull": 85,
    "energy": 15,
    "retentionRisk": "High",
    "growthPotential": 70,
    "weaknessFlags": [
      "Slow Pacing",
      "No CTA",
      "Generic Hashtags",
      "Static Shot"
    ],
    "sound": 10,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "اعتماد مقاطع صوتية رائجة (ترند) ذات طابع هادئ أو روحاني كخلفية موسيقية، حتى لو بمستوى صوت منخفض، لزيادة فرصة ظهور الفيديو.",
    "appearance": 9,
    "appearanceIssue": null,
    "filming": 10,
    "mood": "Contemplative",
    "issue": "المحتوى عالي الجودة وذو طابع تأملي، لكن إيقاعه البطيء والمشاهد الثابتة لا تتناسب مع طبيعة تيك توك السريعة، مما يؤدي إلى انخفاض معدل الاحتفاظ بالجمهور وضعف الانتشار.",
    "suggestion": "اقتطاع أقوى جملة من الفيديو في مقطع قصير جداً (15-20 ثانية). يجب إضافة عناصر بصرية ديناميكية مثل ظهور النص كلمة بكلمة مع المتحدثة، أو استخدام تأثيرات تقريب بطيئة (slow zoom) للحفاظ على انتباه المشاهد. إضافة دعوة واضحة للتفاعل في النهاية (CTA) مثل \"اترك تعليقاً بكلمة 'الحمدلله'\" يمكن أن يزيد من التفاعل بشكل كبير."
  },
  {
    "id": "7617485224183598356",
    "title": "صحتك بالدنيا 🤍\nفذَكّر | نِعم منسية\n#rasayel #vira...",
    "thumbnail": "https://p19-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oUBCAvktxFelGErDQpEDvof2QLGNg3ZPBc2wcR~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=5rT46RBkblVK8oTRkl0DxnNKERQ%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 305,
    "likes": 39,
    "comments": 4,
    "shares": 0,
    "posted": "2026-03-15",
    "duration": 113,
    "score": 78,
    "hook": 90,
    "pacing": 65,
    "caption": 85,
    "hashtags": 60,
    "cta": 10,
    "tone": "Reflective",
    "emotionalPull": 85,
    "energy": 15,
    "retentionRisk": "Medium",
    "growthPotential": 70,
    "weaknessFlags": [
      "No CTA",
      "Slow Pacing",
      "Generic Hashtags"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "صحتك بالدنيا 🤍 فذَكّر | نِعم منسية",
    "soundIssue": null,
    "soundSuggestion": "The audio quality is excellent. Consider adding a trending but calm/atmospheric sound at a very low volume (1-5%) underneath the original audio to potentially boost reach.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Contemplative / Spiritual",
    "issue": "The video's slow, reflective pace and lack of a direct call-to-action limit its engagement potential on a platform optimized for quick interactions.",
    "suggestion": "Add a simple, engaging question in the caption or as text at the end, such as \"ما هي النعمة التي تشعر بالامتنان لها اليوم؟\" (What blessing are you grateful for today?), to encourage comments and community interaction."
  },
  {
    "id": "7616741839932099861",
    "title": "رضا .. الحمد لله 🤍\nفذَكّر | نِعم منسية\n#rasayel #...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/ocybsvAEEhijA80BUAaGhbinBFAYSQbACIas0~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=bzLo1zDEleO8YBsUDBfNqMoR3p8%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 629,
    "likes": 34,
    "comments": 7,
    "shares": 1,
    "posted": "2026-03-13",
    "duration": 121,
    "score": 58,
    "hook": 8,
    "pacing": 5,
    "caption": 6,
    "hashtags": 6,
    "cta": 0,
    "tone": "Spiritual",
    "emotionalPull": 75,
    "energy": 20,
    "retentionRisk": "High",
    "growthPotential": 45,
    "weaknessFlags": [
      "No CTA",
      "Slow Pacing",
      "Low Engagement"
    ],
    "sound": 9,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "استمروا في استخدام موسيقى هادئة تتناسب مع المحتوى، ولكن يمكنكم تجربة وضع الصوت الأصلي على مقطع موسيقي رائج (Trending Sound) لزيادة فرصة الانتشار.",
    "appearance": 9,
    "appearanceIssue": null,
    "filming": 9,
    "mood": "Contemplative",
    "issue": "الفيديو ذو جودة إنتاجية عالية جداً، لكن إيقاعه بطيء وطويل نسبياً لمنصة تيك توك، مما أدى إلى انخفاض نسبة المشاهدة والمشاركة.",
    "suggestion": "قسّموا الرسالة إلى أجزاء أقصر وأكثر تأثيراً. يمكن عمل فيديو مدته 15 ثانية يركز على جملة قوية واحدة من المقطع. أضيفوا سؤالاً في نهاية الفيديو أو في الكابشن لتحفيز التعليقات وزيادة التفاعل."
  },
  {
    "id": "7616023645022080276",
    "title": "الحمد لله عندي ولاد🤍\nفذَكّر | نِعم منسية\n#viralvi...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o8R1EIi1AvKOa7bxAABAIa25Iz0wjBCCAMiKfY~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=03HG0kxqn36pkxg4dmcLllyJscI%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 257,
    "likes": 21,
    "comments": 3,
    "shares": 0,
    "posted": "2026-03-11",
    "duration": 103,
    "score": 85,
    "hook": 90,
    "pacing": 80,
    "caption": 85,
    "hashtags": 40,
    "cta": 0,
    "tone": "Reflective",
    "emotionalPull": 90,
    "energy": 20,
    "retentionRisk": "Medium",
    "growthPotential": 65,
    "weaknessFlags": [
      "Weak Hashtags",
      "No CTA",
      "Slow Pacing for TikTok"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "الصوت ممتاز. يمكن تشجيع الآخرين على استخدام هذا الصوت الأصلي في فيديوهاتهم التأملية لزيادة الانتشار.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 85,
    "mood": "Grateful and Heartfelt",
    "issue": "الفيديو عالي الجودة من حيث الإنتاج، لكن استراتيجية الانتشار على تيك توك ضعيفة. الهاشتاجات عامة جدًا ولا يوجد دعوة للتفاعل (CTA)، مما يحد من وصول الفيديو لجمهوره المستهدف.",
    "suggestion": "استخدموا هاشتاجات أكثر تخصصًا وصلة بالموضوع مثل #نعمة_الاولاد، #تربية، #خواطر_رمضانية، #الأمومة. وأضيفوا دعوة بسيطة للتفاعل في نهاية الفيديو أو في الوصف، مثل: 'شاركنا بنعمة تشعر بالامتنان لوجودها' لزيادة المشاركة."
  },
  {
    "id": "7615276293885545748",
    "title": "لو وقتك من دهب، فأنت بتبيعه بالرخيص🤍\nفذَكّر | نِع...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o8K1Bf8JCiVKIR5UAA0wiB3uEOI3AAT4CAPA91~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=GjGqDa1aqN%2FW9lLke0GFXwu03Bs%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 320,
    "likes": 31,
    "comments": 5,
    "shares": 2,
    "posted": "2026-03-09",
    "duration": 120,
    "score": 85,
    "hook": 95,
    "pacing": 80,
    "caption": 90,
    "hashtags": 60,
    "cta": 10,
    "tone": "Reflective",
    "emotionalPull": 85,
    "energy": 30,
    "retentionRisk": "Low",
    "growthPotential": 80,
    "weaknessFlags": [
      "No CTA",
      "Generic Hashtags"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "The audio is excellent and professional. Maintain this high standard.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 90,
    "mood": "Contemplative",
    "issue": "The video has very high production value and a strong message, but lacks a clear Call to Action (CTA) to drive engagement. This passivity leads to viewers watching and scrolling on without liking, commenting, or following.",
    "suggestion": "Incorporate a direct CTA. End the video by asking a thought-provoking question related to the topic, such as 'ما هي أكثر طريقة تضيع بها وقتك؟' (What is the biggest way you waste your time?). This encourages comments and transforms viewers from passive listeners to active participants."
  },
  {
    "id": "7614519259921730837",
    "title": "ربنا فكرك يعني بيحبك🤍\nفذَكّر | نِعم منسية\n#viralv...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/ogAZNG8oDICJeshkA3FAoIjfwEfTTADEE2AZIW~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=2YcFpVac%2FqeXt5YgD%2BGTKujIKKA%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 265,
    "likes": 34,
    "comments": 7,
    "shares": 0,
    "posted": "2026-03-07",
    "duration": 84,
    "score": 68,
    "hook": 90,
    "pacing": 45,
    "caption": 90,
    "hashtags": 60,
    "cta": 0,
    "tone": "Inspirational",
    "emotionalPull": 95,
    "energy": 20,
    "retentionRisk": "High",
    "growthPotential": 55,
    "weaknessFlags": [
      "Slow Pacing",
      "No CTA",
      "Monolithic Format"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "ربنا فكرك يعني بيحبك🤍 فذَكّر | نِعم منسية",
    "soundIssue": null,
    "soundSuggestion": "استخدام موسيقى تصويرية أكثر تأثيرًا وربما إضافة مؤثرات صوتية خفيفة عند النقاط المحورية لزيادة التأثير العاطفي.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 85,
    "mood": "Contemplative",
    "issue": "الفيديو يعتمد على نسق البودكاست الطويل والبطيء، وهو أسلوب لا يتناسب مع طبيعة منصة تيك توك السريعة، مما يؤدي إلى صعوبة في جذب انتباه المشاهدين والاحتفاظ بهم، وبالتالي ضعف الانتشار رغم جودة الإنتاج العالية.",
    "suggestion": "يجب إعادة تحرير المادة لتناسب تيك توك. يمكن قص الفيديو إلى مقاطع أقصر (15-25 ثانية) يركز كل منها على فكرة قوية واحدة. أضيفوا تأثيرات بصرية مثل الزوم البطيء أو تغيير زاوية التصوير أو استخدام لقطات B-roll ذات صلة بالموضوع لكسر رتابة المشهد الواحد وزيادة الديناميكية."
  },
  {
    "id": "7613780397452807445",
    "title": "كل اللي يجيبه ربنا خير🤍\nفذَكّر | نِعم منسية\n#rasa...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/oYlEmzACPBb2A3ECApiac32AiAaQBLslIhUEY~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=kpSaiRVBqNwMLpETswPmAgUI3oU%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 274,
    "likes": 27,
    "comments": 6,
    "shares": 0,
    "posted": "2026-03-05",
    "duration": 101,
    "score": 68,
    "hook": 90,
    "pacing": 60,
    "caption": 85,
    "hashtags": 70,
    "cta": 0,
    "tone": "Inspirational",
    "emotionalPull": 85,
    "energy": 20,
    "retentionRisk": "High",
    "growthPotential": 60,
    "weaknessFlags": [
      "No CTA",
      "Slow Pacing",
      "Low Energy"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رَسَائِل",
    "soundIssue": null,
    "soundSuggestion": "Encourage viewers to use the sound to share their own stories of blessings, which can increase the audio's virality and lead back to your content.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 90,
    "mood": "Reflective and heartfelt",
    "issue": "The video has excellent production quality but suffers from extremely low reach. Its slow, passive, monologue style, combined with a complete lack of a Call to Action (CTA), fails to generate the engagement (comments, shares) needed to be pushed by the TikTok algorithm.",
    "suggestion": "Add a strong, direct Call to Action at the end of the video using a text overlay and in the caption. For this specific video, a powerful CTA would be: 'منشن لشريك حياتك وقوله شكراً' (Tag your life partner and say thank you). This encourages interaction, shares, and emotional connection, which can significantly boost visibility."
  },
  {
    "id": "7613078268798897429",
    "title": "يا صبر أيوب 🤍\nفذَكّر | نِعم منسية\n#viralvideos #r...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/osXknAv44KAG7iI0C0ifABwjZFLAsbE5IABwCg~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=Vs4NvEAjjtj9j1cMrxfnoHDBv9w%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 338,
    "likes": 21,
    "comments": 6,
    "shares": 1,
    "posted": "2026-03-03",
    "duration": 71,
    "score": 88,
    "hook": 90,
    "pacing": 85,
    "caption": 75,
    "hashtags": 40,
    "cta": 0,
    "tone": "Spiritual",
    "emotionalPull": 85,
    "energy": 20,
    "retentionRisk": "Medium",
    "growthPotential": 90,
    "weaknessFlags": [
      "Weak Hashtags",
      "No CTA"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "Original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "The audio is professionally produced. Encourage others to use this sound for their own reflective videos to increase the content's reach.",
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 90,
    "mood": "Contemplative",
    "issue": "The video's main weakness is its discoverability strategy. The content and production quality are very high, but the use of generic hashtags like #viral and #foryoupage hinders it from reaching its specific target audience. Additionally, the absence of a Call to Action (CTA) misses an opportunity to boost engagement and follower growth.",
    "suggestion": "Optimize the hashtag strategy by using more niche and relevant Arabic tags (e.g., #الصبر, #خواطر_إيمانية, #تذكير, #رمضان_يجمعنا). Also, add a simple CTA in the caption or as a final text overlay, such as 'ما هي أكثر نعمة تشعر بالامتنان لها؟ شاركنا في التعليقات' to encourage discussion and interaction."
  },
  {
    "id": "7612704147292409109",
    "title": "هو اللي بيحصل في العالم ده طبيعي؟!\nاستنوا حلقة خاص...",
    "thumbnail": "https://p19-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o4fpzVRtESDpNLhEehFG1QuEBcZuQgB1cbCcSA~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=6xzMG1m29x%2FNDxpFrunny0Dlz5U%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 42200,
    "likes": 140,
    "comments": 6,
    "shares": 5,
    "posted": "2026-03-02",
    "duration": 61,
    "score": 88,
    "hook": 95,
    "pacing": 98,
    "caption": 90,
    "hashtags": 85,
    "cta": 92,
    "tone": "Dramatic",
    "emotionalPull": 95,
    "energy": 90,
    "retentionRisk": "Low",
    "growthPotential": 90,
    "weaknessFlags": [
      "Low Engagement Ratio"
    ],
    "sound": 98,
    "soundType": "Original Sound",
    "soundName": "Original Sound",
    "soundIssue": null,
    "soundSuggestion": null,
    "appearance": 95,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Suspenseful and alarming",
    "issue": "The video is an excellent, high-energy teaser with a strong hook, but the like-to-view ratio is low. This suggests that while it grabs attention, it doesn't effectively convert viewers into active engagers (likers, commenters).",
    "suggestion": "Enhance the caption's call-to-action to be more interactive. In addition to announcing the episode, pose a direct, thought-provoking question to the audience related to the video's content, such as: 'ما هو أكثر موضوع مقلق تتوقعونه في المستقبل؟ شاركونا في التعليقات'. This encourages immediate discussion and can significantly boost engagement metrics."
  },
  {
    "id": "7612262107551157524",
    "title": "نعمة الوطن 🤍\nفذَكّر | نِعم منسية\n\n#rasayel #ام_ال...",
    "thumbnail": "https://p16-common-sign.tiktokcdn-us.com/tos-alisg-p-0037/o0AQAE5Aj9DITAXfIAiSFF3fn6oDIEFfow6DcK~tplv-tiktokx-origin.image?dr=9636&x-expires=1777557600&x-signature=CiTcYDZZ1Rr7Us2TzaGNPWqaIm8%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=useast8",
    "views": 351,
    "likes": 26,
    "comments": 6,
    "shares": 0,
    "posted": "2026-03-01",
    "duration": 89,
    "score": 48,
    "hook": 30,
    "pacing": 20,
    "caption": 85,
    "hashtags": 75,
    "cta": 0,
    "tone": "Reflective",
    "emotionalPull": 80,
    "energy": 15,
    "retentionRisk": "High",
    "growthPotential": 25,
    "weaknessFlags": [
      "Slow Pacing",
      "Weak Hook",
      "No CTA",
      "Monologue Format"
    ],
    "sound": 95,
    "soundType": "Original Sound",
    "soundName": "original sound - Rasayel | رسائل",
    "soundIssue": null,
    "soundSuggestion": "جودة الصوت ممتازة. يمكن تجربة إضافة موسيقى تريندينج هادئة أو مؤثرة بصوت منخفض جداً تحت الصوت الأصلي لزيادة فرصة الفيديو في الانتشار.",
    "appearance": 90,
    "appearanceIssue": null,
    "filming": 95,
    "mood": "Nostalgic",
    "issue": "الفيديو مصمم كقطعة من بودكاست، بإيقاع بطيء جداً ومونولوج طويل لا يتناسب مع طبيعة تيك توك السريعة. هذا الأسلوب يؤدي إلى فقدان اهتمام المشاهد بسرعة، وهو ما تعكسه الأرقام المنخفضة للمشاهدات والتفاعل.",
    "suggestion": "لزيادة التفاعل، يجب تحويل المقطع ليتناسب مع تيك توك: 1. ابدأوا بأقوى جملة في الفيديو كخطاف فوري مع نص كبير وواضح على الشاشة. 2. أضيفوا مقاطع فيديو ثانوية (B-roll) لشوارع، أشخاص، أو مشاهد تعبر عن الوطن أثناء حديث المتكلمة لكسر رتابة المشهد. 3. استخدموا خاصية الترجمة التلقائية (captions) بشكل ديناميكي لتظهر مع الكلام، مما يساعد على جذب الانتباه. 4. اختتموا الفيديو بسؤال مباشر للمتابعين مثل: 'ما هو أكثر شيء تحبه في وطنك؟' لتحفيز التعليقات."
  }
] as const

export const mockGenerations: any[] = [
  { label: "Gen Z", pct: 52, color: "#D4537E" },
  { label: "Millennials", pct: 31, color: "#378ADD" },
  { label: "Gen X", pct: 12, color: "#5DCAA5" },
  { label: "Boomers", pct: 5, color: "#888780" },
] as const

export const mockTrends: any[] = [
  { rank: 1, name: "Day in my life (agency edition)", type: "format", views: "2.1B" },
  { rank: 2, name: "POV: you hired an agency", type: "format", views: "440M" },
  { rank: 3, name: "Before & after transformation", type: "format", views: "1.4B" },
  { rank: 4, name: "Things I wish I knew earlier", type: "hook", views: "3.2B" },
  { rank: 5, name: "Trending lo-fi beat #4821", type: "sound", views: "890M" },
] as const

export const mockCompetitors: any[] = [
  {
    handle: "@dina_aamer",
    name: "Dina Aamer",
    followers: 0,
    postsThisWeek: 0,
    viewChange: "—",
    status: "stable",
    avgViews: 0,
    topFormat: "—",
    bio: "",
    scrapedAt: null,
    pros: [],
    cons: [],
    contentStrategy: "—",
    postingFrequency: "—",
    avgEngagement: "—",
    topVideoTitle: "—",
    topVideoViews: 0,
    threatLevel: "Medium",
    opportunity: "Click 'Analyze Live' to scrape real data",
    needsScrape: true,
  },
  {
    handle: "@lamiaa.fahmy",
    name: "Lamiaa Fahmy",
    followers: 0,
    postsThisWeek: 0,
    viewChange: "—",
    status: "stable",
    avgViews: 0,
    topFormat: "—",
    bio: "",
    scrapedAt: null,
    pros: [],
    cons: [],
    contentStrategy: "—",
    postingFrequency: "—",
    avgEngagement: "—",
    topVideoTitle: "—",
    topVideoViews: 0,
    threatLevel: "Medium",
    opportunity: "Click 'Analyze Live' to scrape real data",
    needsScrape: true,
  },
] as const

export const mockIdeas: any[] = [
  {
    id: "1",
    hook: "POV: a client came to us with zero presence — here's week 1",
    format: "Before & after",
    act1: "Show the client's empty social profile / zero followers",
    act2: "Walk through the strategy we built in 48 hours",
    act3: "Reveal week 1 results — views, engagements, first viral moment",
    generation: "Gen Z",
    sound: "Trending lo-fi beat",
    caption: "From 0 to real results in 7 days. This is what we actually did. #agencylife #contentmarketing #brandgrowth",
    bestTime: "7:00 PM – 9:00 PM",
    difficulty: "Easy",
    potential: "High",
  },
  {
    id: "2",
    hook: "3 things Egyptian brands do that kill their reach (and how to fix them)",
    format: "List / educational",
    act1: "Introduce the 3 mistakes with bold text overlays",
    act2: "Show real examples of each mistake with quick fixes",
    act3: "Call to action: 'Which one are you guilty of? Comment below'",
    generation: "Millennials",
    sound: "Upbeat background music",
    caption: "Stop doing #3 immediately. #marketing #egyptianbusiness #socialmediatips",
    bestTime: "12:00 PM – 2:00 PM",
    difficulty: "Medium",
    potential: "High",
  },
  {
    id: "3",
    hook: "Day in the life at MAS studio — but make it chaotic",
    format: "DITL",
    act1: "Chaotic morning — 5 clients, 3 deadlines, 1 broken camera",
    act2: "How the team handles it — systems, tools, mindset",
    act3: "End with the win: content delivered, client happy, team exhausted but proud",
    generation: "All",
    sound: "Viral audio of the week",
    caption: "Nobody told us running a studio would look like this. #behindthescenes #studiolife #mas",
    bestTime: "6:00 PM – 8:00 PM",
    difficulty: "Easy",
    potential: "Medium",
  },
] as const
